# Introduction {#intro}


--- 
title: "Gabe's Guide to Engineering"
author: "Gabe Benitez"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::bs4_book: default   # or bookdown::gitbook
documentclass: book
bibliography:
  - book.bib
  - packages.bib
description: >
  This is a living document that is meant to host workflows that I do on engineering projects.
link-citations: true
github-repo: "rstudio/bookdown-demo"
---

I am a Junior Water Resources Engineer-in-Training (EIT) with a goal of developing a living document to share the workflows I use on engineering projects. This guide also serves as a record of lessons learned and opportunities for improvement to help refine my processes over time.

## Disclaimer 

The information and workflows in this book are provided for general educational and informational purposes only. I make no warranties about their completeness, reliability, or accuracy. Use of these methods is at your own risk. I am not liable for any loss, damage, or injury resulting from the application of these workflows.
