
library(tidyr)
library(ggplot2)
library(readr)
library(dplyr)
library(tidyverse)
library(lubridate)
library(viridis)
library(plotly)

df1 <- read_delim("_book/dailyPrecip.csv", delim = "|")

data <- df1 %>%
  rename(Year = "Water Year")

data_long <- data %>%
  pivot_longer(cols = -c(Year, Day),
               names_to = "Month",
               values_to = "Precip")

data_long <- data_long %>%
  mutate(
    MonthNum = match(Month, month.abb),
    Date = make_date(Year, MonthNum, Day),
    MonthNum = NULL
  ) %>%
  mutate(Date = ymd(Date))

# Create a function to reorder months from Oct to Sep
reorder_month <- function(x) {
  factor(x, levels = c("Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"))
}

# Prepare the data for plotting
data_plot <- data_long %>%
  mutate(
    WaterYear = ifelse(month(Date) >= 10, Year, Year - 1),
    Month = reorder_month(Month)
  ) %>%
  filter(Day == days_in_month(Date)) %>%
  arrange(WaterYear, Month)

# Calculate average cumulative precipitation
avg_precip <- data_plot %>%
  group_by(Month) %>%
  summarize(AvgPrecip = mean(Precip, na.rm = TRUE))
  
data_plot$WaterYear <- as.factor(data_plot$WaterYear)

# Create the plot
p <- ggplot() +
  geom_line(data = data_plot, aes(x = Month, y = Precip, group = WaterYear, color = WaterYear), 
            linewidth = 1) +
  geom_line(data = avg_precip, aes(x = Month, y = AvgPrecip, group = 1), 
            linewidth = 1.5, color = "black") +
  geom_point(data = avg_precip, aes(x = Month, y = AvgPrecip), 
             size = 1, color = "black") +
  scale_x_discrete(limits = levels(reorder_month(avg_precip$Month))) +
  scale_color_viridis(discrete = TRUE, option = "plasma", name = "Water Year") +
  labs(
    title = "Average Cumulative Precipitation 2004-2024",
    x = "Month",
    y = "Cumulative Precipitation (Inches)"
  ) +
  theme_minimal() +
  theme(
   legend.position = "right",
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid.minor = element_blank(),
    legend.key = element_rect(fill = "white", colour = NA),
    legend.key.size = unit(0.8, "cm")
  )

plotly_plot <- ggplotly(p)

